DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM microsoft365_capability_health LIMIT 1) THEN
    RAISE EXCEPTION 'MICROSOFT365_CAPABILITY_HEALTH_ROWS_REQUIRE_REVIEW' USING ERRCODE = '55000';
  END IF;
END
$$;

DROP TABLE microsoft365_capability_health;
