LOCK TABLE sites IN ACCESS EXCLUSIVE MODE;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM sites
    WHERE time_zone IS NOT NULL
    LIMIT 1
  ) THEN
    RAISE EXCEPTION 'SITE_TIME_ZONE_ROWS_REQUIRE_REVIEW' USING ERRCODE = '55000';
  END IF;
END
$$;

ALTER TABLE sites
DROP CONSTRAINT sites_time_zone_valid;

ALTER TABLE sites
DROP COLUMN time_zone;
